### ISSUE TITLE
diceware的中文页面显示乱码

### ISSUE THREAD

**Issue by crazypeace** [cfbao/chinese-diceware#2]
这个页面显示是乱码
http://world.std.com/~reinhold/diceware.chinese.html

截图
https://i.loli.net/2019/01/20/5c4433a128589.png

**Comment by cfbao** [comment]
这个页面不是我管的，与我做的中文词表没有直接关系。

这是多年前另有人提供的 Diceware 英文主页的翻译。
Arnold Reinhold 也知道这个页面乱码了，但原始文件已丢失。若有兴趣可以直接联系他提供更新翻译。
